services:
  website:
    image: caddy
    volumes:
      - /home/website/minimalist-page/Caddyfile:/etc/caddy/Caddyfile
      - /home/website/minimalist-page/public:/srv
    ports:
      - "80:80"
      - "443:443"

  strapi:
    image: strapi/strapi
    volumes:
      - ./app:/srv/app
    depends_on:
      - website
